name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
#      - name: Workflow data
#        run: echo "${{ toJson(github.event) }}"
      - name: Run Telegram Notify Action
        uses: proDreams/actions-telegram-notifier@dev
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          status: ${{ job.status }}
          notify_fields: "actor,repository,workflow"
          message: "Test message."
          footer: "Test footer"
